# Install and configure PostgreSQL including setup our user & database
---

- dynamic_defaults:
    hostvars: '{{ hostvars[inventory_hostname] }}'
    defaults: '{{ postgresql_dynamic_defaults }}'
    must_match: yes
  tags: [postgresql, always]

- name: Install PostgreSQL packages
  package:
    name: '{{ postgresql_packages }}'
    state: present
  become: yes
  tags: [postgresql, packages]

- block:
    - name: Initialize PostgreSQL
      command: >
        {{ postgresql_bin_directory }}/initdb
        --pgdata {{ postgresql_data_directory }}
        {{ postgresql_initdb_options|join(' ') }}
      args:
        creates: '{{ postgresql_data_directory }}/PG_VERSION'
      become_user: postgres
      environment:
        PATH: '{{ postgresql_bin_directory }}:$PATH'
        LD_LIBRARY_PATH: '{{ postgresql_lib_directory }}:$LD_LIBRARY_PATH'

    - name: Create PostgreSQL directories
      file:
        path: '{{ item }}'
        owner: postgres
        group: postgres
        mode: 0700
        state: directory
      loop:
        - '{{ postgresql_data_directory }}/conf.d'

    - name: Configure PostgreSQL
      template:
        src: '{{ postgresql_config_file }}'
        dest: '{{ postgresql_config_directory }}/postgresql.conf'
        mode: 0644
      notify: restart postgresql

    - name: Configure PostgreSQL allowed hosts
      template:
        src: pg_hba.conf.j2
        dest: '{{ postgresql_config_directory }}/pg_hba.conf'
        mode: 0644
      notify: restart postgresql
  become: yes
  tags: [postgresql, config]

- name: Start PostgreSQL service
  service:
    name: '{{ postgresql_service }}'
    enabled: yes
    state: started
  become: yes
  tags: [postgresql, services]

- block:
    - name: Install PostGIS packages
      package:
        name:
          - postgis
          - 'postgresql-{{ postgresql_version }}-postgis-2.1'
          - 'postgresql-{{ postgresql_version }}-postgis-2.1-scripts'
        state: present

    - name: Install geolocation prerequisites required for all back-ends
      package:
        name:
          - binutils
          - libgeos-3.4.2
          - libgeos-c1
          - libgeos-dev
        state: present

    - name: Install geolocation prerequisites required for PostgreSQL and SQLite
      package:
        name:
          - libproj-dev
          - proj-bin
          - proj-data
        state: present

    - name: Install geolocation prerequisites optional but required for SQLite
      package:
        name:
          - gdal-bin
          - libgdal1-dev
          - python3-gdal
        state: present

    - name: install optional IP-based geolocation library
      package:
        name:
          - libgeoip1
        state: present

  become: yes
  tags: [postgresql, packages]
  when: "'postgis' in postgresql_extensions"

- include_role:
    name: postgresql-databases
  tags: [postgresql, databases]
  when: postgresql_is_master|bool
