---

- name: Install PostgreSQL packages
  package:
    name: '{{ postgresql_packages }}'
    state: present
  become: yes
  tags: [postgresql, packages]  # FIXME Remove when this is fixed https://github.com/ansible/ansible/issues/30882
