---

- name: Install PostgreSQL packages
  yum:
    name: '{{ postgresql_packages }}'
    enablerepo: '{{ postgresql_yum_enablerepo }}'
    state: present
  become: yes
  tags: [postgresql, packages]  # FIXME Remove when this is fixed https://github.com/ansible/ansible/issues/30882
