---

- name: Install PostgreSQL packages
  ansible.builtin.package:
    name: '{{ postgresql_packages }}'
    state: present
  become: true
  tags: [postgresql, packages]  # FIXME Remove when this is fixed https://github.com/ansible/ansible/issues/30882

...
