---

- block:
    - name: Register TimescaleDB apt key
      ansible.builtin.apt_key:
        url: '{{ postgresql_timescaledb_apt_key }}'
        state: present

    - name: Install TimescaleDB apt repository
      ansible.builtin.apt_repository:
        repo: '{{ postgresql_timescaledb_apt_repository }}'
        filename: ansible_roles_postgresql_timescaledb
        state: present
        update_cache: true
  become: true
  tags: [postgresql, packages]  # FIXME Remove when this is fixed https://github.com/ansible/ansible/issues/30882

...
